backend:
  # This is just for testing, no real data saved anywhere
  name: git-gateway
  branch: master

media_folder: "/static/img/uploads"
public_folder: "/static/img/uploads"

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: single_file

  # Required - a list of locales to show in the editor UI
  locales: [it, en]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: it

collections:
  - label: "Posts"
    name: "post"
    folder: "source/posts"
    slug: "{{slug}}"
    create: true
    i18n: true
    editor:
      preview: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post.njk", i18n: duplicate }
      - { label: "Title", name: "title", widget: "string", i18n: true}
      - { label: "Description", name: "description", widget: "string", i18n: true }
      - { label: "Publish Date", name: "date", widget: "date", i18n: duplicate }
      - { label: "Featured image", name: "featuredImage", widget: "image", i18n: duplicate }
      - { label: "Contenuto", name: "body", widget: "markdown", i18n: true }